# Permalinks
permalink:           pretty

# Setup
title:               From 0 to Data Scientist in 12 weeks
tagline:             
url:                 http://christianbuerkle.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Christian buerkle    
  url:               
  email:             Jchristianbuerkle@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/christianbuerkle

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
